version: "3.7"
services:
  pikabu_control:
    image: flowork/pikabu-control-dev:latest
    volumes:
      - type: bind
        source: .
        target: /go/src/pikabu-control
      - type: bind
        source: /home/wonsuck_song/wordpress/www/html
        target: /frontend
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
         cpus: "1.0"
         memory: 1000M
    ports:
      - 9000:8080
    networks:
      - develop_network
networks:
  develop_network:
